name: Build DXC macOS arm64

on:
  push:
    tags:
      - "v*"
      - "release-*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-macos-arm64:
    name: Build DXC (macOS arm64)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve latest DXC release tag
        id: dxc_tag
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.getLatestRelease({ owner: 'microsoft', repo: 'DirectXShaderCompiler' });
            core.setOutput('tag', data.tag_name);

      - name: Checkout DXC (upstream)
        uses: actions/checkout@v4
        with:
          repository: microsoft/DirectXShaderCompiler
          ref: ${{ steps.dxc_tag.outputs.tag }}
          fetch-depth: 0
          submodules: true
          path: dxc

      - name: Build
        id: build
        shell: pwsh
        run: |
          pwsh -File ./build_osx_arm64.ps1 -ProjectDir "$env:GITHUB_WORKSPACE/dxc" -Config Release

      - name: Show artifact path
        if: always()
        shell: pwsh
        run: |
          Write-Host "Artifact from build step: ${{ steps.build.outputs.artifact }}"

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.tar.gz
          fail_on_unmatched_files: true

      - name: Upload artifact (backup)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dxc-macos-arm64
          path: artifacts/*.tar.gz
          retention-days: 1
